/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dataBarang;

import com.mysql.jdbc.Util;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.text.SimpleDateFormat;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Adilah Qurrotu'Aini
 */
public class FormKaryawan extends javax.swing.JFrame {
    Connection con;
    Statement st;
    ResultSet rs;
    
    public void showDate() {
        Date td = new Date();
        SimpleDateFormat t = new SimpleDateFormat("dd-MM-yyyy");
        txtDate.setText(t.format(td));
    }

    /**
     * Creates new form FormKaryawan
     */
    public FormKaryawan() {
        dB = new KoneksiDB();
        this.setExtendedState(Login.MAXIMIZED_VERT);
        initComponents();
        showTable();
        showDate();
    }
    
    void username (String user) {
        txtUser.setText(user);
    }
    
    public static Connection getConnection() {
        Connection connection = null;
        String driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://localhost/db_penjualan"; 
        String user = "root";
        String password = "";
        if (connection == null) {
            try {
                Class.forName(driver);
                connection = DriverManager.getConnection(url, user, password);
                System.out.println("Koneksi berhasil");
            } catch (ClassNotFoundException | SQLException error) {
               System.exit(0);
            }

        }
        return connection;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtKodeKry = new javax.swing.JTextField();
        txtNamaKry = new javax.swing.JTextField();
        txtAlamatKry = new javax.swing.JTextField();
        txtNoTelp = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        btnTambahKry = new javax.swing.JButton();
        btnUbahKry = new javax.swing.JButton();
        btnHapusKry = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtpPass = new javax.swing.JPasswordField();
        btnX = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKry = new javax.swing.JTable();
        btnRepKry = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCariKry = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DATA KARYAWAN");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/user (2).png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/calendar.png"))); // NOI18N

        txtUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUser.setEnabled(false);

        txtDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDate.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Kode Karyawan");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Nama Karyawan");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Alamat");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("No Telepon");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Username");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Password");

        txtKodeKry.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKodeKry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeKryActionPerformed(evt);
            }
        });

        txtNamaKry.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtAlamatKry.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNoTelp.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnTambahKry.setBackground(new java.awt.Color(255, 255, 255));
        btnTambahKry.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambahKry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/add.png"))); // NOI18N
        btnTambahKry.setText("TAMBAH");
        btnTambahKry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKryActionPerformed(evt);
            }
        });

        btnUbahKry.setBackground(new java.awt.Color(255, 255, 255));
        btnUbahKry.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbahKry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/edit.png"))); // NOI18N
        btnUbahKry.setText("UBAH");
        btnUbahKry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahKryActionPerformed(evt);
            }
        });

        btnHapusKry.setBackground(new java.awt.Color(255, 255, 255));
        btnHapusKry.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapusKry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/trash.png"))); // NOI18N
        btnHapusKry.setText("HAPUS");
        btnHapusKry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusKryActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Data Karyawan");

        txtpPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnX.setBackground(new java.awt.Color(255, 255, 255));
        btnX.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnX.setForeground(new java.awt.Color(255, 255, 255));
        btnX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cancel.png"))); // NOI18N
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 123, 255));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("DATA KARYAWAN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblKry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKry);

        btnRepKry.setBackground(new java.awt.Color(255, 255, 255));
        btnRepKry.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRepKry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer.png"))); // NOI18N
        btnRepKry.setText("CETAK");
        btnRepKry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepKryActionPerformed(evt);
            }
        });

        btnClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sweeping.png"))); // NOI18N
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("CARI KARYAWAN");

        txtCariKry.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCariKry.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCariKry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariKryActionPerformed(evt);
            }
        });
        txtCariKry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCariKryKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAlamatKry)
                    .addComponent(txtNamaKry, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtpPass)
                    .addComponent(txtusername)
                    .addComponent(txtNoTelp)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHapusKry, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTambahKry))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRepKry, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(btnUbahKry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtKodeKry, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClean)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCariKry, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnX, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(txtCariKry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(btnClean)
                                .addComponent(txtKodeKry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(btnX)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamaKry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlamatKry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTambahKry, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUbahKry))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHapusKry)
                            .addComponent(btnRepKry)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahKryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKryActionPerformed
        String kodeKry, namaKry, alamatKry, notelpKry, username, pass;
        kodeKry = txtKodeKry.getText();
        namaKry = txtNamaKry.getText();
        alamatKry = txtAlamatKry.getText();
        notelpKry = txtNoTelp.getText();
        username = txtusername.getText();
        pass = txtpPass.getText();
        dB.insertBDK(kodeKry, namaKry, alamatKry, notelpKry, username, pass);
        JOptionPane.showMessageDialog(rootPane, "Karyawan Berhasil Ditambahkan!", 
                "Penambahan Karyawan", JOptionPane.INFORMATION_MESSAGE);
        showTable();
        txtNamaKry.setText("");
        txtAlamatKry.setText("");
        txtNoTelp.setText("");
        txtusername.setText("");
        txtpPass.setText("");
        txtKodeKry.setText("");
//        autonumberBrg();
    }//GEN-LAST:event_btnTambahKryActionPerformed

    private void btnHapusKryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusKryActionPerformed
        String kodeKry;
        kodeKry = txtKodeKry.getText();
        dB.deleteDBK(kodeKry);
        JOptionPane.showConfirmDialog(rootPane, "Anda Yakin Ingin Menghapus Karyawan?",
                "Penghapusan Karyawan", JOptionPane.YES_NO_OPTION);
        JOptionPane.showMessageDialog(rootPane, "Karyawan Berhasil Dihapus!", 
                "Penghapusan Karyawan", JOptionPane.INFORMATION_MESSAGE);
        showTable();
        txtNamaKry.setText("");
        txtAlamatKry.setText("");
        txtNoTelp.setText("");
        txtusername.setText("");
        txtpPass.setText("");
    }//GEN-LAST:event_btnHapusKryActionPerformed

    private void btnUbahKryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahKryActionPerformed
        String kodeKry, namaKry, alamatKry, notelpKry, username, pass;
        kodeKry = txtKodeKry.getText();
        namaKry = txtNamaKry.getText();
        alamatKry = txtAlamatKry.getText();
        notelpKry = txtNoTelp.getText();
        username = txtusername.getText();
        pass = txtpPass.getText();
        dB.updateBDK(kodeKry, namaKry, notelpKry, alamatKry, username, pass);
        JOptionPane.showConfirmDialog(rootPane, "Anda Yakin Ingin Mengubah Karyawan?",
                    "Perubahan Karyawan", JOptionPane.YES_NO_OPTION);
        JOptionPane.showMessageDialog(this, "Karyawan Berhasil Diubah!", "Perubahan Karyawan",
                JOptionPane.INFORMATION_MESSAGE);
        showTable();
        txtNamaKry.setText("");
        txtAlamatKry.setText("");
        txtNoTelp.setText("");
        txtusername.setText("");
        txtpPass.setText("");
        txtKodeKry.setText("");
    }//GEN-LAST:event_btnUbahKryActionPerformed

    private void tblKryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKryMouseClicked
        int row = tblKry.getSelectedRow();
        txtKodeKry.setText(tblKry.getValueAt(row, 0).toString());
        txtNamaKry.setText(tblKry.getValueAt(row, 1).toString());
        txtAlamatKry.setText(tblKry.getValueAt(row, 2).toString());
        txtNoTelp.setText(tblKry.getValueAt(row, 3).toString());
        txtusername.setText(tblKry.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tblKryMouseClicked

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        String user = txtUser.getText();
        FormWellcome fk = new FormWellcome();
        fk.setVisible(true);
        fk.username(user);
        dispose();
    }//GEN-LAST:event_btnXActionPerformed

    private void txtKodeKryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeKryActionPerformed

    }//GEN-LAST:event_txtKodeKryActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        txtNamaKry.setText("");
        txtAlamatKry.setText("");
        txtNoTelp.setText("");
        txtusername.setText("");
        txtpPass.setText("");
        txtKodeKry.setText("");
    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnRepKryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepKryActionPerformed
        try {
            File namafile = new File("src/report/reportKaryawan.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnRepKryActionPerformed

    private void txtCariKryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariKryActionPerformed
        showTable();
    }//GEN-LAST:event_txtCariKryActionPerformed

    private void txtCariKryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKryKeyTyped
        showTable();
    }//GEN-LAST:event_txtCariKryKeyTyped

    public void showTable() {
        try {
            String cari = txtCariKry.getText();
            tbmKry = new DefaultTableModel(new String[] {"Kode Karyawan", "Nama Karyawan", "Alamat", "No Telepon", "Username"}, 0);
            ResultSet rs;
            rs = dB.selectDBK("data_kry where nama_kry LIKE '%"+ cari +"%'");
            while (rs.next()) {
                tbmKry.addRow(new Object[] {rs.getString("kd_kry"),
                    rs.getString("nama_kry"), rs.getString("alamat"),
                    rs.getString("no_telp"), rs.getString("username")}); 
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormKaryawan.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblKry.setModel(tbmKry);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKaryawan().setVisible(true);
            }
        });
    }

    KoneksiDB dB;
    DefaultTableModel tbmKry;    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnHapusKry;
    private javax.swing.JButton btnRepKry;
    private javax.swing.JButton btnTambahKry;
    private javax.swing.JButton btnUbahKry;
    private javax.swing.JButton btnX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKry;
    private javax.swing.JTextField txtAlamatKry;
    private javax.swing.JTextField txtCariKry;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtKodeKry;
    private javax.swing.JTextField txtNamaKry;
    private javax.swing.JTextField txtNoTelp;
    private javax.swing.JTextField txtUser;
    private javax.swing.JPasswordField txtpPass;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
